apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: lsyc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lsyc
    app.kubernetes.io/part-of: byoc-app-czso
  name: lsyc
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: lsyc
status:
  loadBalancer: {}
